### ISSUE TITLE
new times always say in 4 hours or 4 hours ago

### ISSUE THREAD

**Issue by eddwinn** [miguelgrinberg/Flask-Moment#34]
Hello,
If an item is less than 4 hours old, it will say in 4 hours or 4 hours ago.  After 4 hours it utilizes correct time.

`moment = Moment(app)`
```

    {{ moment.include_jquery() }}
    {{ moment.include_moment() }}
```
`timestamp = datetime.now()`
`<td width="10%">{{ moment(timestamp=rate.timestamp, local=True).fromTime(now)  }}`

where now = datetime.now()
I also have tried ..

`moment(timestamp=rate.timestamp, local=False).fromNow(no_suffix = False)`

**Comment by miguelgrinberg** [comment]
I'm not sure how this extension can cause this problem for you, since it just passes the timestamps that you provide directly into moment.js.

Did you look at the page source? The timestamps all have a `<span>` wrapper that shows the UTC time that was rendered. You may want to check those to see if they match the times that you think you are passing as argument.

**Comment by eddwinn** [comment]
in my models i hate datetime.utcnow instead of datetime.now

**Comment by miguelgrinberg** [comment]
@eddwinn You should always use UTC timestamps in your server.
